# Generated by Django 4.2.2 on 2023-06-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ef11_app', '0004_product_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount_price',
        ),
    ]
