# Generated by Django 4.2.2 on 2023-06-19 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ef11_app', '0003_category_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.IntegerField(default=45),
            preserve_default=False,
        ),
    ]
